// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Upload, doc;
  $ = require('jquery');
  doc = document;
  Upload = function() {};
  Upload.prototype = {
    /*
     * 上传文件
    */

    _updata: function(_data, _callback) {
      return $.ajax({
        url: 'upload.php',
        type: 'post',
        data: _data,
        processData: false,
        contentType: false,
        sucdess: function(_res) {
          return _callback(_res);
        }
      });
    },
    /*
     * 处理文件
     * @param {Array} _files 上传的文件数组
    */

    _checkFiles: function(_files) {
      var formData;
      formData = new FormData();
      $.each(_files, function(_index, _item) {
        console.log(_item);
        return formData.append('images[]', _item);
      });
      this._updata(formData, function(data) {
        return console.log(data);
      });
    },
    /*
     * 文件选择按钮绑定事件
     * @param {String} _id  文件选择按钮
    */

    _bind: function(_id) {
      var self;
      self = this;
      $(doc).delegate(_id, 'change', function(ev) {
        var files;
        files = ev.target.files;
        self._checkFiles(files);
      });
    },
    /*
     * 初始化
     * @param {String} _id  文件选择按钮
     * @return
    */

    init: function(_id) {
      this._bind(_id);
    }
  };
  module.exports = Upload;
});
