// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Upload, doc;
  $ = require("jquery");
  doc = document;
  /*
   * 创建上传对象
  */

  Upload = function() {};
  console.log($);
  Upload.prototype = {
    /*
     * 给上传按钮绑定事件
     * @param {String} _id 上传按钮对象
     * @return
    */

    _bind: function(_id) {
      $(doc).delegate(_id, 'change', function(_e) {
        console.log(_e);
      });
    },
    /*
     * 初始化
     * @param {String} _id 上传按钮对象
     * @return
    */

    init: function(_id) {
      this._bind(_id);
    }
  };
  module.exports = Upload;
});
